### ISSUE TITLE
Argument Bug In The SCT's Forward Function

### ISSUE THREAD

**Issue by palakornb** [mrpeerat/SCT#1]
สวัสดีครับ 

ผมพบว่า tutorial ที่อยู่ใน github (https://github.com/mrpeerat/Thai-Sentence-Vector-Benchmark/blob/main/SCT-Thai.ipynb) ยังมีประเด็นที่ว่า code ที่ให้มาใน tutorials ยังมี bug ที่ทำให้ผมรันตาม tutorials ได้ โดยบั้คที่เจอ จะอยู่ใน function forward ของ SCTLoss ที่ต้องการ argument มากกว่าที่กำหนดไว้ โดยมี argument ที่ขาดไปคือ rep_sent_en_t ตามในรูปของฟังก์ชันดังนี้

![image](https://github.com/mrpeerat/SCT/assets/37754544/381ea487-d400-490d-b5e2-f0b40566c684)
รูป Forward Function

![image](https://github.com/mrpeerat/SCT/assets/37754544/37b1086b-d573-413e-bf2d-d02af3664d63)
![image](https://github.com/mrpeerat/SCT/assets/37754544/3da8a259-865a-4850-8cf6-8811c78f8d2a)
รูปบั้คที่เกิดขึ้นจากในไฟล์ tutorials

โดยในเบื้องต้น ผมได้แนบไฟล์ jupyter notebook ที่ผมใช้มา zip file นี้ (
[llm_training.zip](https://github.com/mrpeerat/SCT/files/14916445/llm_training.zip)
) ผมอยากรบกวนขอคำแนะนำในการแก้บั้คนี้ด้วยได้ไหมครับ

ขอบคุณมากนะครับ

**Comment by mrpeerat** [comment]
ไฟล์ notebook ตรง dataloader ต้องใช้คำสั่ง 
`train_samples.append(InputExample(texts=[en_text, non_en_text],label=[en_teacher,non_en_teacher]))`
ก็คือต้องมี en_text + non_en_text ครับ 
ตอนนี้ในไฟล์ที่ส่งมาให้ มีแค่
`train_samples.append(InputExample(texts=[en_text],label=[en_teacher]))`
ลองดูได้จาก https://github.com/mrpeerat/Thai-Sentence-Vector-Benchmark/blob/main/SCT-Thai.ipynb (บล็อกที่ 8) or https://github.com/mrpeerat/SCT/blob/main/SCT_main.py#L130

**Comment by palakornb** [comment]
@mrpeerat 
ในกรณีของ SCT Distillation เข้าใจว่าจะต้องเป็น
`train_samples.append(InputExample(texts=[en_text, non_en_text],label=[en_teacher,non_en_teacher]))`

แต่ในกรณีของ SCT เฉยๆ เข้าใจว่า code ควรจะต้องเป็น
`train_samples.append(InputExample(texts=[en_text],label=[en_teacher]))`

ใช่หรือไม่นะครับ ซึ่งต่อให้ลองทำตามในแบบที่ training objective เป็นแบบ distillation แล้ว แล้วก็ลองรัน trainer ด้วย objective แบบ distllation แล้ว ก็ยังเจอปัญหานี้อยู่ดีครับ เพียงแต่เจอเคสที่ว่า argument ที่ต้องการ จะเป็น 4 ตัวแทนที่จะเป็น 2 ตัวอย่างในรูปครับ

**Comment by mrpeerat** [comment]
อันนี้แบบเต็มๆครับ พึ่งเห็นว่าโพสก่อนหน้ามันผิดนิดหน่อย
ถ้าเป็น distillation
`train_samples.append(InputExample(texts=[en_text, non_en_text],label=[en_teacher,non_en_teacher]))`
ถ้าไม่ใช่ distillation
`train_samples.append(InputExample(texts=[en_text, non_en_text]))`

**Comment by palakornb** [comment]
@mrpeerat คิดว่าน่าจะได้แล้วครับ ขอบคุณมากๆนะครับ
